apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-neon-kafka-exporter
  labels:
    k8s-app: plugin-neon-kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: plugin-neon-kafka-exporter
  template:
    metadata:
      labels:
        k8s-app: plugin-neon-kafka-exporter
    spec:
      containers:
      - name: plugin-neon-kafka-exporter
        image: registry.sagecontinuum.org/iperezx/neon-kafka-exporter:0.4.0
        args: ["--mode", "stream","--topic","reading.sensor.prt"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: neon-env
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi